# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9032231dada7209479017746565b41aa397dfa78962c4069169b5ce7bafd6626bd0a6ac47fdd1c26ef53e7df2b076103115f8ad162610bd11f584689854787aa

test:
  secret_key_base: e923c340a2e7329a948a50e7d89f6cd8df63399569f761ce4705b14cc3a7dd69f5772445ee8bc805207ec450570c967186fce2b81709fc9673d8618368e2f483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
